before_install:
  - docker build -t sachin/docker-react -f Dockerfile.dev .
script:
  - docker run sachin/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-455074858100"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"